bk-changeset-1.1560.1.44 balay@asterix.mcs.anl.gov|ChangeSet|20031029182540|17270 ChangeSet   1.1560.1.44 03/10/29 12:25:40 balay@asterix.mcs.anl.gov +1 -0   petscarch now check if the PETSC_DIR specified is a valid one   bug fix for arches with a '-' in the name - for eg: linux-gnu
  bin/petscarch
    1.14 03/10/29 12:25:39 balay@asterix.mcs.anl.gov +8 -2
    petscarch now check if the PETSC_DIR specified is a valid one
    bug fix for arches with a '-' in the name - for eg: linux-gnu


Hg-commit: 32de181e929671d652688362144317137cd94789

diff --git a/bin/petscarch b/bin/petscarch
--- a/bin/petscarch
+++ b/bin/petscarch
@@ -103,6 +103,12 @@ if [ $# -gt 0 ]; then
         echo 'You must indicate the path of PETSc with the environmental variable PETSC_DIR to get suggestions'
         exit 0
      fi
+   else
+      # Test if the PETSC_DIR is a valid dir
+      if ! [ -f ${PETSC_DIR}/include/petscversion.h ]; then
+        echo "PETSC_DIR is currently set to $PETSC_DIR which is invalid. Please set the correct value."
+        exit 0
+      fi
   fi
   
   # try to get configure arch
@@ -119,9 +125,9 @@ fi
 # Now check if there is an installed set of libraries
 
 if [ "${PETSC_DIR}" != "" ]; then
-    ls ${PETSC_DIR}/lib/libg/${LARCH}*/libpetscdm*.* > /dev/null 2>&1
+    ls ${PETSC_DIR}/lib/libg/${LARCH}*/libpetscdm*.* | head -1 > /dev/null 2>&1
     if [ $? -eq 0 ]; then
-	LARCH=`ls -t ${PETSC_DIR}/lib/libg/${LARCH}*/libpetscdm*.* | head -1 | sed -e "s?${PETSC_DIR}/lib/lib[gO_c+omplex]*/\([_a-zA-Z0-9]*\)/libpetscdm.[a-zA-Z0-9]*?\1?g"`
+	LARCH=`ls -t ${PETSC_DIR}/lib/libg/${LARCH}*/libpetscdm*.* | head -1 | sed -e "s?${PETSC_DIR}/lib/lib[gO_c+omplex]*/\([_a-zA-Z0-9\-]*\)/libpetscdm.[a-zA-Z0-9]*?\1?g"`
     else 
 	# check if there is a configure installed version
         ${PETSC_DIR}/bin/configarch > /dev/null 2>&1
