edit jenkins script

diff --git a/bin/sendToJenkins b/bin/sendToJenkins
--- a/bin/sendToJenkins
+++ b/bin/sendToJenkins
@@ -1,4 +1,9 @@
 #!/bin/bash 
+function jsonval {
+    temp=`echo $json | sed 's/\\\\\//\//g' | sed 's/[{}]//g' | awk -v k="text" '{n=split($0,a,","); for (i=1; i<=n; i++) print a[i]}' | sed 's/\"\:\"/\|/g' | sed 's/[\,]/ /g' | sed 's/\"//g' | grep -w $prop`
+    echo ${temp##*|}
+}
+ 
 OPTIND=1
 username=""
 branch="next"
@@ -6,8 +11,9 @@ address="default"
 architecture="none"
 configoptions=""
 silent="no"
+query=""
 
-while getopts "h?a:b:m:o:su:" opt; do
+while getopts "h?a:b:m:o:q:su:" opt; do
   case "$opt" in
     h|\?)
       echo "sendToJenkins script"
@@ -25,6 +31,7 @@ while getopts "h?a:b:m:o:su:" opt; do
       echo "            Use 'none' if no email desired"
       echo "         -o <configure options>             -- default is empty"
       echo '            Example: -o "--with-complex --with-precision=single" '
+      echo "         -q <number>                    -- query results for job number"
       echo "         -s                                 -- silent"
       echo "         -u <username on login.mcs.anl.gov> -- default is empty"
       exit 0
@@ -46,6 +53,9 @@ while getopts "h?a:b:m:o:su:" opt; do
      configoptions=${configoptions//=/%3D}
      configoptions="\&configure_options=${configoptions}"
      ;;
+    q)
+     query=${OPTARG}
+     ;;
     u)
      username=$OPTARG+'@'
      ;;
@@ -58,16 +68,13 @@ while getopts "h?a:b:m:o:su:" opt; do
   esac
 done
 
+
 if [ -z ${username} ]; then
   url=login.mcs.anl.gov
 else
   url=${username}+login.mcs.anl.gov
 fi;
 
-if [ ${address} == "default" ]; then
-  echo "Error: No email address give. Use -m <email> or -m none"
-  exit 1
-fi;
 
 # set up connection through named proxy
 command="ssh -M -S jenkins-proxy -fnNT ${url}"
@@ -78,6 +85,15 @@ else
    ${command} 2> /dev/null
 fi
 
+if [ "x${query}" != "x" ]; then
+  ssh -S jenkins-proxy login.mcs.anl.gov curl -s https://jenkins-ci.mcs.anl.gov/job/petsc-branch/${query}/api/json | python -mjson.tool
+  exit 0
+fi
+
+if [ ${address} == "default" ]; then
+  echo "Error: No email address give. Use -m <email> or -m none"
+  exit 1
+fi;
 
 if [ ${architecture} == "short" ]; then
   #linux-gcc-real linux-gcc-real-opt linux-gxx-complex linux-dbg-quad osx-10.6 osx-10.6-cxx-cmplx-pkgs-dbg linux-uni; do
@@ -85,15 +101,29 @@ if [ ${architecture} == "short" ]; then
     command="ssh -S jenkins-proxy ${url} curl -s -X POST https://jenkins-ci.mcs.anl.gov/job/petsc-branch/buildWithParameters?branch=${branch}${mailto}\&named_test=${arch}${configoptions}"
     if [ ${silent} == "no" ]; then
 	echo "${command}"
-    fi
+    fi 
     ${command}
+    json = `"ssh -S jenkins-proxy ${url} curl -s https://jenkins-ci.mcs.anl.gov/job/petsc-branch/api/json"`
+    prop = lastBuild.number
+    lbn = `jsonval`
+    prop= lastBuild.url
+    lburl = `jsonval`
+    echo $lbn $lburl
   done
 else
   command="ssh -S jenkins-proxy ${url} curl -s -X POST https://jenkins-ci.mcs.anl.gov/job/petsc-branch/buildWithParameters?branch='${branch}'${mailto}\&named_test=${architecture}${configoptions}"
   if [ ${silent} == "no" ]; then
       echo "${command}"
   fi
+
+  bn=`ssh -S jenkins-proxy login.mcs.anl.gov curl -s https://jenkins-ci.mcs.anl.gov/job/petsc-branch/api/json | python -c 'import sys,json; print json.load(sys.stdin)["nextBuildNumber"]'`
+
+  echo buildnumber=$bn
   ${command}
+  buildurl=`ssh -S jenkins-proxy login.mcs.anl.gov curl -s https://jenkins-ci.mcs.anl.gov/job/petsc-branch/api/json | python -c 'import sys,json; print json.load(sys.stdin)["url"]'`
+  echo buildpage=$buildurl$bn
+  echo "for build status, visit above url or enter command:"
+  echo $buildurl$bn/api/json \| python -mjson.tool
 fi
 
 
