configure: /usr/bin/python might not exist in newer distributions
Reported-by: Jacob Faibussowitsch <jacob.fai@gmail.com>
Reported-by: Sajid Ali <sajidsyed2021@u.northwestern.edu>

Authored-by: Jacob Faibussowitsch <jacob.fai@gmail.com>
Authored-by: Jed Brown <jed@jedbrown.org>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,13 @@
-#!/usr/bin/env python
+#!/bin/sh
+
+"true" '''\'
+for pyimpl in python3 python python2; do
+  which $pyimpl > /dev/null 2>&1  && echo "Using $pyimpl for Python" && exec $pyimpl "$0" "$@"
+done
+echo "Error! Could not locate python! Please install and have python3, python, or python2 in PATH."
+echo "Or use: /path/to/valid/python configure $@"
+exit 127
+'''
 
 import sys, os
 
