sh-compatible petscmpiexec
include valgrind suppression files into tarball

diff --git a/lib/petsc/bin/petscmpiexec b/lib/petsc/bin/petscmpiexec
--- a/lib/petsc/bin/petscmpiexec
+++ b/lib/petsc/bin/petscmpiexec
@@ -1,82 +1,68 @@
-#! /bin/csh -f
-# $Id: petscmpiexec,v 1.3 2001/09/04 16:18:05 bsmith Exp $ 
-#
+#!/usr/bin/env sh
+
 #    Uses PETSC_ARCH and PETSC_DIR plus the MPIEXEC command in
 #  packages to run mpiexec
 #    Use PETSCVALGRIND_OPTIONS and MPI_BINDING from environment
 #
-if ($1 == '-h' | $1 == '--help') then
+if [ $1 = '-h' ] || [ $1 = '--help' ]; then
   echo "Usage: petscmpiexec <-valgrind> <-debugger> -n <numberprocessors> programname <programopions>"
   exit
-endif
+fi
 
-set valgrind=0
-set debugger=0
-if ( x$1 == x"-valgrind" ) then
-  set valgrind = 1
-  echo $2
-  if ( x$2 == x"-debugger" ) then
-    set debugger=1
+valgrind=0
+debugger=0
+if [ x$1 = x"-valgrind" ]; then
+  valgrind=1
+  if [ x$2 = x"-debugger" ]; then
+    debugger=1
     shift
-  endif
+  fi
   shift
-endif
+fi
 
-if ( $1 !=  "-n" ) then
+if [ $1 != "-n" ]; then
   echo "Error in  mpiexec command: must start with -n <numberprocessors> or -valgrind -n <numberprocessors>"
   exit 1
-endif
+fi
 shift
-set np=$1
+np=$1
 shift
 
-set hosts=""
-if ( x$1 ==  x"-hosts" ) then
+hosts=""
+if [ x$1 = x"-hosts" ]; then
   shift
-  set hosts="-hosts $1"
+  hosts="-hosts $1"
   shift
-endif
+fi
 
-set MPI_BUILD_HOME = `grep MPI_BUILD_HOME ${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables | grep -v mpiexec | grep -v include | grep -v lib | grep -v "#MPI_HOME" | cut -f2 -d=`
-set MPI_HOME = `grep "MPI_HOME " ${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables | grep -v build | grep -v include | grep -v "#MPI_HOME" | grep -v mpe  | cut -f2 -d=`
-set run = `grep MPIEXEC ${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables | grep -v "#MPIEXEC" | grep -v MPIEXECEXECUTABLE | cut -f2 -d=`
+if [ ! -f "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/files" ]; then
+  echo "Error build location not found! Please set PETSC_DIR and PETSC_ARCH correctly for this build."
+  exit 1
+fi
 
-#echo $MPI_BUILD_HOME
-#echo $MPI_HOME
+MPI_BUILD_HOME=$(grep MPI_BUILD_HOME "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables" | grep -v mpiexec | grep -v include | grep -v lib | grep -v "#MPI_HOME" | cut -f2 -d=)
+MPI_HOME=$(grep "MPI_HOME " "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables" | grep -v build | grep -v include | grep -v "#MPI_HOME" | grep -v mpe  | cut -f2 -d=)
+run=$(grep MPIEXEC "${PETSC_DIR}/${PETSC_ARCH}/lib/petsc/conf/petscvariables" | grep -v "#MPIEXEC" | grep -v MPIEXECEXECUTABLE | cut -f2 -d=)
 
-#echo $run
-set trun = `echo ${run} | sed -e sz\$MPI_BUILD_HOMEz${MPI_BUILD_HOME}z`
-#echo $trun
-set nrun = `echo ${trun} | sed -e sz\$MPI_HOMEz${MPI_HOME}z`
-#echo $nrun
-set qrun = `echo ${nrun} | sed -e sz\$PETSC_DIRz${PETSC_DIR}z`
-#echo $qrun
+trun=$(echo ${run} | sed -e "s,\$MPI_BUILD_HOME,${MPI_BUILD_HOME},")
+nrun=$(echo ${trun} | sed -e "s,\$MPI_HOME,${MPI_HOME},")
+qrun=$(echo ${nrun} | sed -e "s,\$PETSC_DIR,${PETSC_DIR},")
 
-#echo $qrun $*
-
-if ! $?MPI_BINDING then
-  set MPI_BINDING=
-endif
-
-if ( ${valgrind} == "1" ) then
-  if ! $?PETSCVALGRIND_OPTIONS then
-    set PETSCVALGRIND_OPTIONS=
-  endif
-  set VALGRIND_CMD=`which valgrind`
-  set VALGRIND_OPTIONS="-q --tool=memcheck  --num-callers=20 --track-origins=yes --suppressions=${PETSC_DIR}/lib/petsc/bin/maint/petsc-val.supp --error-exitcode=10 ${PETSCVALGRIND_OPTIONS}"
-  if ( ${debugger} == "1" ) then
-    set VALGRIND_CMD="xterm -e ${VALGRIND_CMD}"
-    set VALGRIND_OPTIONS="${VALGRIND_OPTIONS} --db-attach=yes"
-  endif
-  if ( `uname` == 'Darwin') then
-    set VALGRIND_OPTIONS="${VALGRIND_OPTIONS} --dsymutil=yes"
-  endif
+if [ ${valgrind} = "1" ]; then
+  VALGRIND_CMD=$(which valgrind)
+  VALGRIND_OPTIONS="-q --tool=memcheck  --num-callers=20 --track-origins=yes --suppressions=${PETSC_DIR}/share/petsc/valgrind/petsc-val.supp --error-exitcode=10 ${PETSCVALGRIND_OPTIONS}"
+  if [ ${debugger} = "1" ]; then
+    VALGRIND_CMD="xterm -e ${VALGRIND_CMD}"
+    VALGRIND_OPTIONS="${VALGRIND_OPTIONS} --db-attach=yes"
+  fi
+  if [ `uname` = 'Darwin' ]; then
+    VALGRIND_OPTIONS="${VALGRIND_OPTIONS} --dsymutil=yes"
+  fi
   $qrun -n $np $hosts ${VALGRIND_CMD} ${VALGRIND_OPTIONS} $*
-  if ( `uname` == 'Darwin') then
+  if [ `uname` = 'Darwin' ]; then
     rm -rf *.dSYM
     rm -rf ${PETSC_DIR}/${PETSC_ARCH}/lib/lib*.dSYM
-  endif
+  fi
 else
   $qrun -n $np $hosts ${MPI_BINDING} $*
-endif
-
+fi
