move x11 test from 'make test' to 'make testx11'
Hg-commit: 3ce766a9375800d3f2a588b61ebfa734f22ba0bc

diff --git a/src/snes/examples/tutorials/makefile b/src/snes/examples/tutorials/makefile
--- a/src/snes/examples/tutorials/makefile
+++ b/src/snes/examples/tutorials/makefile
@@ -484,16 +484,26 @@ testex19: ex19.PETSc
 	   else echo "Possible error running C/C++ src/snes/examples/tutorials/ex19 with 2 MPI processes"; \
            echo "See http://www.mcs.anl.gov/petsc/petsc-as/documentation/troubleshooting.html";\
            cat ex19_1.tmp; fi; fi; \
-        D2=`grep "#define PETSC_HAVE_X11 1" ${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h`; \
-        if [ "$$?" = 0 ]; then \
-           ${MPIEXEC} -n 1 ./ex19 -dmmg_nlevels 4 -snes_monitor_draw  > ex19_1.tmp 2>&1; \
-	   if (${DIFF} output/ex19_1.testout ex19_1.tmp > /dev/null 2>&1) then \
-           echo "Graphics example src/snes/examples/tutorials/ex19 run successfully with 1 MPI process"; \
-	   else echo "Possible error running Graphics examples src/snes/examples/tutorials/ex19 1 MPI process"; \
-           echo "See http://www.mcs.anl.gov/petsc/petsc-as/documentation/troubleshooting.html";\
-           cat ex19_1.tmp; fi; fi; \
-           ${RM} -f ex19_1.tmp; \
-           ${MAKE} PETSC_ARCH=${PETSC_ARCH} PETSC_DIR=${PETSC_DIR} ex19.rm ; fi
+        ${RM} -f ex19_1.tmp; \
+        ${MAKE} PETSC_ARCH=${PETSC_ARCH} PETSC_DIR=${PETSC_DIR} ex19.rm ; fi
+
+testx11ex19: ex19.PETSc
+	-@if [ "${PETSC_WITH_BATCH}" != "" ]; then \
+           echo "Running with batch filesystem; to test run src/snes/examples/tutorials/ex19 with" ; \
+           echo "your systems batch system"; \
+	elif [ -f ex19 ]; then \
+          D2=`grep "#define PETSC_HAVE_X11 1" ${PETSC_DIR}/${PETSC_ARCH}/include/petscconf.h`; \
+          if [ "$$?" = 0 ]; then \
+             ${MPIEXEC} -n 1 ./ex19 -dmmg_nlevels 4 -snes_monitor_draw  > ex19_1.tmp 2>&1; \
+	     if (${DIFF} output/ex19_1.testout ex19_1.tmp > /dev/null 2>&1) then \
+             echo "Graphics example src/snes/examples/tutorials/ex19 run successfully with 1 MPI process"; \
+	     else echo "Possible error running Graphics examples src/snes/examples/tutorials/ex19 1 MPI process"; \
+             echo "See http://www.mcs.anl.gov/petsc/petsc-as/documentation/troubleshooting.html";\
+             cat ex19_1.tmp; fi; \
+	  else echo "PETSc installed without X11. Not running src/snes/examples/tutorials/ex19"; fi; \
+        ${RM} -f ex19_1.tmp; \
+        ${MAKE} PETSC_ARCH=${PETSC_ARCH} PETSC_DIR=${PETSC_DIR} ex19.rm ; fi
+
 runex21:
 	-@${MPIEXEC} -n 4 ./ex21  -snes_mf -snes_monitor_short -nox > ex21_1.tmp 2>&1; \
 	   if (${DIFF} output/ex21_1.out ex21_1.tmp) then true; \
