bk-changeset-1.199 knepley@spinetta.mcs.anl.gov|ChangeSet|20011126192452|19735 ChangeSet   1.199 01/11/26 13:24:52 knepley@spinetta.mcs.anl.gov +1 -0   Added a check that run targets exist for all examples, and that these   targets are probably exercised.
  bmake/common/rules
    1.12 01/11/26 13:24:51 knepley@spinetta.mcs.anl.gov +37 -0
    Added a check that run targets exist for all examples, and that these
    targets are probably exercised.


Hg-commit: 5005a992b97e51c437673ca93b1687a772bcd345

diff --git a/bmake/common/rules b/bmake/common/rules
--- a/bmake/common/rules
+++ b/bmake/common/rules
@@ -714,6 +714,43 @@ checkbadSource:
        fi; \
          done
 
+checkTestCoverage:
+	-@for filename in ex*.c; do \
+	  if test -f $$filename; then \
+	    if ! grep run`basename $$filename .c`\: makefile 2>&1 > /dev/null; then \
+	      echo "Missing run target for `pwd`/$$filename"; \
+	    elif ! grep run`basename $$filename .c`\  makefile 2>&1 > /dev/null; then \
+	      echo "Missing test for `pwd`/$$filename"; \
+	    fi; \
+	  fi; \
+	done
+	-@for filename in ex*.f; do \
+	  if test -f $$filename; then \
+	    if ! grep run`basename $$filename .f`\: makefile 2>&1 > /dev/null; then \
+	      echo "Missing run target for `pwd`/$$filename"; \
+	    elif ! grep run`basename $$filename .f`\  makefile 2>&1 > /dev/null; then \
+	      echo "Missing test for `pwd`/$$filename"; \
+	    fi; \
+	  fi; \
+	done
+	-@for filename in ex*.F; do \
+	  if test -f $$filename; then \
+	    if ! grep run`basename $$filename .F`\: makefile 2>&1 > /dev/null; then \
+	      echo "Missing run target for `pwd`/$$filename"; \
+	    elif ! grep run`basename $$filename .F`\  makefile 2>&1 > /dev/null; then \
+	      echo "Missing test for `pwd`/$$filename"; \
+	    fi; \
+	  fi; \
+	done
+	-@for filename in ex*.f90; do \
+	  if test -f $$filename; then \
+	    if ! grep run`basename $$filename .f90`\: makefile 2>&1 > /dev/null; then \
+	      echo "Missing run target for `pwd`/$$filename"; \
+	    elif ! grep run`basename $$filename .f90`\  makefile 2>&1 > /dev/null; then \
+	      echo "Missing test for `pwd`/$$filename"; \
+	    fi; \
+	  fi; \
+	done
 
 #
 # fixfortran target is used in one of the stages of generating the fortran
